payload:
  - DOMAIN,api.steampowered.com
  - DOMAIN,store.steampowered.com
  - DOMAIN-SUFFIX,fanatical.com
  - DOMAIN-SUFFIX,humblebundle.com
  - DOMAIN-SUFFIX,steam-chat.com
  - DOMAIN-SUFFIX,steamcdn-a.akamaihd.net
  - DOMAIN-SUFFIX,steamcommunity.com
  - DOMAIN-SUFFIX,steamcontent.com
  - DOMAIN-SUFFIX,steamgames.com
  - DOMAIN-SUFFIX,steamstat.us
  - DOMAIN-SUFFIX,steamstatic.com
  - DOMAIN-SUFFIX,steamusercontent.com
  - DOMAIN-SUFFIX,epicgames.com
  - DOMAIN-SUFFIX,ol.epicgames.com
  - DOMAIN-SUFFIX,helpshift.com
  - DOMAIN-SUFFIX,paragon.com
  - DOMAIN-SUFFIX,unrealengine.com
  - DOMAIN,public-ubiservices.ubi.com
  - DOMAIN,static3.cdn.ubi.com
  - DOMAIN,ubisoft-uplay-savegames.s3.amazonaws.com
  - DOMAIN,ubisoft-orbit-savegames.s3.amazonaws.com
  - DOMAIN,public-im-ubiservices.ubi.com
  - DOMAIN,msr-public-ubiservices.ubi.com
  - DOMAIN,public-ws.aws-ubiservices.ubi.com
  - DOMAIN,public.aws-ubiservices.ubi.com
  - DOMAIN,public-ws-ubiservices.ubi.com
  - DOMAIN,api-ubiservices.ubi.com
  - DOMAIN,lb-upc-dmx.ubisoft.com
  - DOMAIN,msr-api-ubiservices.ubi.com
  - DOMAIN,dmx.upc.ubisoft.com
  
